name: "Suit & Tie"
description: "We're two young wedding videographers from Louisiana who enjoy making creative, memorable videos."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: true
